const types = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  LOG_IN: "LOG_IN",
  LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
  LOG_IN_FAILURE: "LOG_IN_FAILURE",
  LOG_OUT: "LOG_OUT",
  SIGN_UP: "SIGN_UP",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SHOW_SIGN_UP_CONFIRMATION_MODAL: "SHOW_SIGN_UP_CONFIRMATION_MODAL",
  CONFIRM_SIGN_UP: "CONFIRM_SIGNUP",
  CONFIRM_SIGN_UP_SUCCESS: "CONFIRM_SIGNUP_SUCCESS",
  CONFIRM_SIGN_UP_FAILURE: "CONFIRM_SIGNUP_FAILURE"
};

export default types;
